name = "remember-pages"
main = "workers.js"
compatibility_date = "2026-01-15"
workers_dev = true

routes = [{ pattern = "rem.furry.ist/*", zone_name = "furry.ist" }]

[vars]
TURNSTILE_SITE_KEY = ""

[[r2_buckets]]
binding = "REMEMBER_DATA"
bucket_name = "remember-data"

[[kv_namespaces]]
binding = "REMEMBER_KV"
id = "00000000000000000000000000000000"
